// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String webClientId = '514431532526-7tunelqplf2mjf126dvsj646g9c42nj4.apps.googleusercontent.com';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBqEIyC17BQddQA5nl1solujvaBXvEtejc",
    authDomain: "komet-7f48b.firebaseapp.com",
    projectId: "komet-7f48b",
    storageBucket: "komet-7f48b.firebasestorage.app",
    messagingSenderId: "514431532526",
    appId: "1:514431532526:web:b43b9de091b4d43ace22ff",
    measurementId: "G-MDS7LVS1XJ",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_H2LzdT9TvGWSQm57mkebFzXSWSQ2dM',
    appId: '1:514431532526:android:3009728676242d93867c31',
    messagingSenderId: '514431532526',
    projectId: 'komet-7f48b',
    storageBucket: 'komet-7f48b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'komet-7f48b',
    storageBucket: 'komet-7f48b.firebasestorage.app',
    iosBundleId: 'com.example.kometApp',
  );
}
